// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nczuxcxaprbayalicoae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jenV4Y3hhcHJiYXlhbGljb2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5NzQ0NjQsImV4cCI6MjA3NTU1MDQ2NH0.al9194D4SMRZWvNBYRHMQMzSp0Kyq3d7LpEZwpZUzLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});